/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author renemm
 */
public class VistaDC extends javax.swing.JFrame {

    /**
     * Creates new form VistaDC
     */
    public VistaDC() {
        initComponents();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenPane = new javax.swing.JPanel();
        layered_pane = new javax.swing.JLayeredPane();
        panel1 = new javax.swing.JPanel();
        txt_num_ticket = new javax.swing.JTextField();
        btn_cambios = new javax.swing.JButton();
        btn_dev = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        layered_pane.setLayout(new java.awt.GridLayout());

        txt_num_ticket.setText("02983791");
        txt_num_ticket.setToolTipText("Ingresa Numero de ticket");
        txt_num_ticket.setVisible(false);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(txt_num_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(txt_num_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        layered_pane.add(panel1);

        btn_cambios.setText("Cambios");

        btn_dev.setText("Devoluciones");

        javax.swing.GroupLayout contenPaneLayout = new javax.swing.GroupLayout(contenPane);
        contenPane.setLayout(contenPaneLayout);
        contenPaneLayout.setHorizontalGroup(
            contenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenPaneLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btn_dev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cambios)
                .addGap(98, 98, 98))
            .addGroup(contenPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layered_pane))
        );
        contenPaneLayout.setVerticalGroup(
            contenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenPaneLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(contenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cambios)
                    .addComponent(btn_dev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(layered_pane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(contenPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaDC().setVisible(true);
//            }
//        });
//    } 

    public JButton getBtn_cambios() {
        return btn_cambios;
    }

    public void setBtn_cambios(JButton btn_cambios) {
        this.btn_cambios = btn_cambios;
    }

    public JButton getBtn_devoluciones() {
        return btn_dev;
    }

    public void setBtn_devoluciones(JButton btn_devoluciones) {
        this.btn_dev = btn_devoluciones;
    }
    
    public JLayeredPane getLayered_pane() {
        return layered_pane;
    }
    

//    public JPanel getPnl_verifi_compra() {
//        return pnl_verifi_compra;
//    }

    public JTextField getTxt_num_ticket() {
        return txt_num_ticket;
    }

    public JPanel getPanel1() {
        return panel1;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cambios;
    private javax.swing.JButton btn_dev;
    private javax.swing.JPanel contenPane;
    private javax.swing.JLayeredPane layered_pane;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField txt_num_ticket;
    // End of variables declaration//GEN-END:variables

    
}
